services:
  - type: web
    name: medstore-api
    env: python
    plan: free
    rootDir: backend
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask db upgrade && python -m flask seed && python -m gunicorn app:app --config gunicorn.conf.py
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medstore-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://e-pharmacy-sigma-mauve.vercel.app,https://your-frontend.vercel.app,https://your-frontend.netlify.app,http://localhost:3000
      - key: JWT_EXPIRES_HOURS
        value: "12"
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: medstore-postgres
    plan: free
    databaseName: medstore
    user: medstore
